name: Deploy Astro to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to hommet.ch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install deps and build
        run: |
          npm ci
          npm run build

      - name: Deploy with rsync
        uses: burnett01/rsync-deployments@v1.0.2
        with:
          switches: -avzr --delete
          path: dist/
          remote_path: /home/milan/services/portfolio/dist
          remote_host: hommet.ch
          remote_user: milan
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
